---
title: "A comprehensive research of the social factors that influence homelessness in Los Angeles"
subtitle: "An essay for Fall Data Challenge: Help Solve Homelessness"
author:
- Xinyue Tang^[Undergraduate in Computer Science & Engineering, Department of Computer Science, University of California, Davis. (xiytang@ucdavis.edu)]
- Chen Wang^[Undergraduate in Computer Engineering, Samueli School of Engineering, University of California, Irvine. (chenw23@uci.edu)]
date: "10/27/2019"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    keep_tex: true
---

\newpage

# Overview of homeless population in Los Angeles

## Data Collection

We used the statistical data retrieved from U.S. Bureau of Labor Statistics[^1], Zillow Group[^2] and California Department of Public Health[^3] to provide a general impression of trend and status quo of the homeless people and sheltered homeless people in Los Angeles. The figure showing this perspective is on the slides page 2 and 3.

[^1]: U.S. Bureau of Labor Statistics. (2019, September). BLS Data Finder 1.1. Retrieved from https://www.bls.gov/data/.

[^2]: Zillow Group. (2019, September). Houses For Rent in Los Angeles CA - 2,651 Homes | Zillow. Retrieved from https://www.zillow.com/los-angeles-ca/rent-houses/.

[^3]: California Department of Public Health. (2019, September). CDPH Home. Retrieved from https://www.cdph.ca.gov/.

## Analysis of the situation of the homeless population

From the figure, we can have a strong impression that in Los Angeles, there are as many as ¾ of the homeless people that are not sheltered yet. Furthermore, the overall homeless population is increasing significantly in recent years. However, what disappoints us is that the shelterings that government can provide for the homeless people is generally not increasing. They remain the same in the decade and therefore making the contradiction of shelter need and the providing of shelter even more severe.


# Analysis of the factors influencing homelessness

## Factors considered and data source

After having a knowledge of the general fact of homeless people in Los Angeles, we have dug much deeper into the reasons that lead to the severity of homelessness. We have searched and collected data from U.S. Bureau of Labor Statistics[^1] including the Consumption Price Index(CPI), Minimum Wages, Unemployment rate, House rental price and drug addict population in the city of Los Angeles.

## Principal Component Analysis

We want to examine whether and how these factors affect the results. Here we implement the Principal Component Analysis method to process the data. The factors we consider include CPI, minimum wages, unemployment rate, house rental price and drug addictive population.

### Processing steps for Principal Component Analysis

For the first step, because the data value differ greatly in terms of units and absolute value, we used Standardization into a range from 0 to 1 so that the different values will be able to compare with each other. After standardization, we imported the data into R and utilized the princomp function to perform the principal component analysis. From the result, we can see that the first component has a Proportion of Variance at 93%, while the first two components have a Proportion of Variance of 97%. This means the factors are in a highly uniform trend and can be reduced to only one or two dimensions. After our looking more thoroughly into the principal component analysis result, we will find out from  the loadings of the factors to the components, the five factors we are observing are having almost equal relation with the dependent variable - the overall homeless population. Therefore, we can conclude that these factors possess a strong effect on the overall homeless people. 

### Reasoning for the result from Principal Component Analysis

The increasing price index and house rental prices make living expenses even higher for people with lower income and the rising unemployment rate may make more people homeless. What’s more, drug addiction, as a common but severe social phenomenon, is also becoming more severe in Los Angeles and we cannot deny the possibility that there are many people who fall into homelessness due to drug addiction. 


# Advice proposed to the government

In conclusion, we are calling for the government to take various measures to curb this phenomenon both from the source and from the result. They can enhance the infrastructure construction to provide more shelter for the homeless people to relieve this problem soon. They can also take measures like providing drug rehabilitation programs, providing more temporary working opportunities for the unemployed people, controlling house rental price or providing more alternative housing for low income population and so on. 

